services:
  web:
    build: .
    command: bundle exec rails s -e production
    environment:
      RAILS_ENV: production
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    depends_on:
      - db
    healthcheck:
      test: "test -f /app/tmp/sockets/puma.sock;echo $? || exit 1"
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 30s
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.33
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  nginx:
    build:
      context: containers/nginx
    volumes:
      # - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - 80:80
    depends_on:
      web:
        condition: service_healthy

volumes:
  db-volume:
  tmp:
  public: